version: "3.8"
services:
  # MONGO
  mongodb:
    image: 'mongo'
    container_name: mongodb
    volumes:
      - data:/data/db
    env_file:
      - ./env/mongo.env
  # Node Backend
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  # FrontEnd
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: